---
title: "Early exploration"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(lubridate)
library(here)

load(file = here("data/processed_data.RData"))

playerData <- playerData %>% 
  filter(round <= 23)
```

## Data overview

```{r}
skim_view <- playerData %>% 
  skimr::skim()
```

## Discrete variables (#13)

```{r}
summarise_brownlow_discrete <- function(df,.simplify = TRUE){
  df %>% 
    {if(.simplify) mutate(.,brownlowVotes = if_else(brownlowVotes > 0,"Vote","No_vote")) else .} %>% 
    group_by(brownlowVotes,.add = TRUE) %>% 
    summarise(n = n()) %>% 
    mutate(pct = n/sum(n))
}

playerData %>% 
  summarise_brownlow_discrete()
```

-   homeTeam
-   awayTeam
-   position
-   teamStatus
-   teamName
-   umpire1
-   umpire2
-   umpire3
-   umpire4

```{r}
playerData %>% 
  group_by(teamName) %>% 
  summarise_brownlow_discrete() %>% 
  ungroup() %>% 
  pivot_wider(names_from = brownlowVotes,values_from = c(n,pct)) %>% 
  arrange(-pct_Vote)
```



## Continuous variables (#14)


```{r}
skim_view %>% 
  filter(skim_type == "numeric") %>% 
  pull(skim_variable)

```

```{r}
playerData %>% 
  count(brownlowVotes,inside50S) %>% 
  ggplot(aes(inside50S,y = n)) +
  geom_col() +
  facet_wrap(~brownlowVotes,scales = "free_y",ncol = 1)
```

```{r}
playerData %>% 
  count(brownlowVotes,contestedMarks) %>% 
  ggplot(aes(contestedMarks,y = n)) +
  geom_col() +
  facet_wrap(~brownlowVotes,scales = "free_y",ncol = 1)
```

```{r}
playerData %>% 
  count(brownlowVotes,disposals) %>% 
  ggplot(aes(disposals,y = n)) +
  geom_col() +
  facet_wrap(~brownlowVotes,scales = "free_y",ncol = 1)
```
```{r}
playerData %>% 
  count(brownlowVotes,tackles) %>% 
  ggplot(aes(tackles,y = n)) +
  geom_col() +
  facet_wrap(~brownlowVotes,scales = "free_y",ncol = 1)
```

```{r}
playerData %>% 
  filter(season == "2021",round == "5",awayTeam == "Richmond",timeOnGroundPercentage > 50) %>% 
  transmute(full_name = paste(givenName,surname),
            full_name = fct_reorder(full_name,brownlowVotes),
            teamName,brownlowVotes,disposals,goals,behinds,inside50S) %>% 
  pivot_longer(cols = c(disposals,goals,behinds,inside50S)) %>% 
  ggplot(aes(value,y = full_name, col = factor(brownlowVotes))) +
  geom_point() +
  facet_grid(.~name,scales = "free_x")
```

